### ISSUE TITLE
double et triple indentation au sein d'une liste

### ISSUE THREAD

**Issue by gllmAR** [tim-montmorency/compendium#3]
il semble y avoir une discrépance entre le preview markdown et le résultat post processing

exemple foncitonne dans le preview markdown, mais qui ne fonctionnne devrait fonctionner

```markdown
* liste 1
    * liste imbriquée 2
        * liste imbriqué 3 
```
mais ça, ça semble fonctionner (nombre de tab + espaces est plus grand que la spécification markdown, voir Françoise pour détail)
```markdown
* liste 1
      * liste imbriquée 2
          * liste imbriquée 3 
```

**Comment by jfcmontmorency** [comment]
Related issue : https://github.com/squidfunk/mkdocs-material/issues/6509

À tester : https://pypi.org/project/mdx-truly-sane-lists/

**Comment by jfcmontmorency** [comment]
Ça a réglé le problème ;)
Merci pour l'issue @gllmAR
